name: Deploy to Netlify
on:
  pull_request:
    types: [review_requested]
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - if: github.event.review.state == 'approved'
        run: |
          # Merge code into main branch
          git checkout main
          git merge gh-pages
          git push origin main
          curl -X POST \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls \
            -H 'Content-Type: application/json' \
            -d '{
              "title": "Automated PR for changes",
              "body": "This PR contains changes from the previous PR",
              "head": "main",
              "base": "gh-pages"
            }'
            
    
    
   