name: production build
on:
  push:
    branches:
    - build
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            branches:
              - build
      - if: true
        run: |
             cd website/app
             bun run build
             bun run deploy