name: production build
on:
  push:
    branches:
    - production
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - if: false
        run: |
             cd website/app
             apt update
             apt install 
             bun run build
             bun run deploy
      - name: Post build results to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = github.context.pullRequest.number;
            const buildResults = 'Build erfolgreich!';
            github.issues.createComment({
              issue_number: prNumber,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              body: buildResults
            });